language:
  node_js
node_js:
  - "5"
cache:
  apt: true
  ccache:
  directories:
    - bison
    - node_modules
sudo: true
env:
  global:
    - GCC_VERSION=5
addons:
 apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
# ensure these match GCC_VERSION
      - gcc-5
      - g++-5
      - binutils
      - gawk
      - build-essential
      - wget
      - libtool
      - flex
      - npm
before_script:
  - sudo npm install -g babel-cli
  - export CC=/usr/bin/gcc-${GCC_VERSION} CXX=/usr/bin/g++-${GCC_VERSION};
  - wget --no-check-certificate http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.gz
  - mkdir $HOME/bison
  - tar -xf bison-3.0.4.tar.gz; cd bison-3.0.4; ./configure --prefix=$HOME/bison; make -j 4 install; cd $PWD/..;
  - export PATH=$HOME/bison/bin:$PATH
script:
  - ${CC} --version ; ${CXX} --version;
  - bison --version
  - pwd
  - ls -la $HOME
  - env
  - make && make test
notifications:
  slack: qut-ifn660-javascript:L91Jp7bz9fqP8fL4gudNYu1G
