#pragma once
#include <cstdarg>
#include <cstdio>
#include <string>
#include <vector>
#include "node.hpp"
#include "script.hpp"
#include "statement.hpp"
#include "expression.hpp"
#include "../type/type.hpp"
#include "../builtin/core.hpp"
#include "../builtin/console.hpp"
